import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Next Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lorem, ipsum.</h1>
      <h2>Lorem, ipsum.</h2>
      <h3>Lorem, ipsum.</h3>
      <h4>Lorem, ipsum.</h4>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, vero!
      </p>
      <a href="#">Link</a>

      <div className="container">
        <span>Text with container</span>

        <div className="card">
          <span>This is a card example</span>
        </div>
      </div>
      <div className="container-soft">
        <h2>This is a container soft</h2>
        <button className="btn btn-primary">This is a button</button>
        <button className="btn btn-warning">This is a button</button>
        <button className="btn btn-danger">This is a button</button>
        <a href="#" className="btn btn-secondary">
          This is a link
        </a>{" "}
      </div>
      <div className="container-soft bg-primary color-black p-1 mt-1">
        <h2>This is a container soft</h2>
        <p className="color-white">You can use margins and paddings. Also you can use customs colors</p>
      </div>

      <div className='card container mt-2'>
        <div className="card-title">
          <h2>This is a card example.</h2>
        </div>
        <div className="card-body">
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, vero!
          </p>
        </div>
        <div className="card-footer pb-1">
          <a href="#" className='btn btn-primary'>Link</a>
        </div>
      </div>

    </div>
  );
}

export default Home
